var rule = {
    title:'腾云驾雾-腾讯视频',
    host:'https://v.qq.com',
    url:'/channel/filter/$cateId-0-0-0-0-0-$sortBy',
    searchUrl:'/x/search/?q=**',
    headers:{
        'User-Agent':'MOBILE_UA'
    },
    timeout:5000,
    class_name:'电影&电视剧&综艺&动漫&纪录片',
    class_url:'1&2&3&4&5',
    play_parse:true,
    lazy:'',
    limit:6,
    double:true,
    推荐:'',
    一级:'',
    二级:'',
    搜索:''
}
